### ISSUE TITLE
New update does not show the map correctly

### ISSUE THREAD

**Issue by smartmeter** [megaboich/js-map-parser#3]
Hello, I just updated, and the left map does not show all the functions in 2015 and community version

Suggestions:
1.   would it be possible to show functions (anonymous vs named) and objects in different colors.
2.   drag and drop sections in the code map to move the code around in source window

**Comment by megaboich** [comment]
Hi,

> left map does not show all the functions 

It would be great if you attach some samples - source code and screenshots are welcome

> show functions (anonymous vs named) and objects in different colors.

That is possible and not very hard to implement. But right now anonymous functions got a special (?) icon in the tree. Isn't it enough?

> drag and drop sections in the code map to move the code around in source window

That is really nice concept, but I am not sure about complexity. It seems far beyond my expectations of simple plugin that shows the code map. In general I am sure that source code must be developed in text editor and must be separated through a lot of files - just to separate all logic. This plugin shows code map only for navigating purposes - sometimes you have old legacy code written in giant single file, or code is bundled together and you don't have sources.

**Comment by powersparks** [comment]
I am seeing a similar issue with jQuery anonymous functions. "click" should have the "#button". see attached image

![capture](https://cloud.githubusercontent.com/assets/12630742/11350671/c46f8254-91d6-11e5-9b16-868855e6894f.PNG)

**Comment by megaboich** [comment]
Hi powersparks,
Thanks for your interest.
Indeed, that was behavior in previous version that anonymous function aliases were containing parameter values from calling function. But that functionality was a bit buggy in case of call chaining.
Also after some consideration I decided to shorten aliases in order to clean up structure, because all that parameters were providing a noise. 
And also I am not a big fan of anonymous functions that really contains important logic, why not just give name to them? It would help in many cases, especially in profiler to find if it consumes a lot of time during script execution.

```
$('#button').click(function buttonClickHandler(){
  alert('');
});
```

Or even separate that function and not inline it to parameters at all?
Thanks for your patience,
Olek.

P.S. I would update release notes for new version to mention this change in behavior.

**Comment by smartmeter** [comment]
ok

**Comment by powersparks** [comment]
That's a great suggestion, I agree.... anonymous functions makes it hard to document too.
